changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Estimation
      labels:
        - estimation
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - internal
